### ISSUE TITLE
Looking forward to the code :)

### ISSUE THREAD

**Issue by ucalyptus** [ppope/dimensions#1]

**Comment by elcronos** [comment]
The same here. Very interesting paper !

**Comment by PenguinJunk** [comment]
Agreed!

**Comment by yusukefukuju** [comment]
me too !

**Comment by ppope** [comment]
Hi all, sorry for the delay. Stay tuned for the code release. I hope to have it out soon.

**Comment by masora1030** [comment]
It is a very nice paper and I read it with great interest.
What time will the script used in this paper be available?
Please let me know if you don't mind.
Thanks.

**Comment by ppope** [comment]
Initial release is now live. Sorry for the late wait!
